trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  displayName: run tests and make jar
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'check assemble'

- task: CopyFiles@1
  displayName: copy jar
  inputs:
    SourceFolder: 'application/build/libs'
    Contents: 'demo-app.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: True

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: demoapp
